### ISSUE TITLE
need help on cmake build error

### ISSUE THREAD

**Issue by gaowayne** [ThinkParQ/beegfs#14]
**Describe the bug**
A clear and concise description of what the bug is, which component (mgmtd, meta, storage, client, others or any combination) is affected and what effects (error messages, performance degradation, crashes, ...) can be observed.
```
it is simple cmake build error. 
```
**Describe the system**
A short description of the system BeeGFS is running on that covers all information relevant to the issue. For example (but not limited to):

 
**To Reproduce**
1. mkdir build1
2. cd build1 cmake .. then make
```
[ 21%] Building CXX object common/CMakeFiles/test-common.dir/tests/TestBitStore.cpp.o
[ 21%] Building CXX object common/CMakeFiles/test-common.dir/tests/TestTargetCapacityPools.cpp.o
[ 21%] Building CXX object common/CMakeFiles/test-common.dir/tests/TestStorageTk.cpp.o
[ 22%] Building CXX object common/CMakeFiles/test-common.dir/tests/TestStripePattern.cpp.o
[ 22%] Building CXX object common/CMakeFiles/test-common.dir/tests/TestListTk.cpp.o
[ 22%] Building CXX object common/CMakeFiles/test-common.dir/tests/TestTimerQueue.cpp.o
[ 22%] Linking CXX executable test-common
[ 22%] Built target test-common
[ 22%] Building CXX object common/CMakeFiles/beegfs_ib.dir/ib_lib/net/sock/ibvsocket/IBVSocket.cpp.o
[ 22%] Building CXX object common/CMakeFiles/beegfs_ib.dir/ib_lib/RDMASocketImpl.cpp.o
[ 23%] Linking CXX shared library libbeegfs_ib.so
[ 23%] Built target beegfs_ib
[ 23%] Building CXX object ctl/CMakeFiles/ctl.dir/source/toolkit/IoctlTk.cpp.o
In file included from /mnt/nvme2n1/wayne/beegfs/beegfs/client_devel/include/beegfs/beegfs.h:4,
                 from /mnt/nvme2n1/wayne/beegfs/beegfs/ctl/source/toolkit/IoctlTk.h:6,
                 from /mnt/nvme2n1/wayne/beegfs/beegfs/ctl/source/toolkit/IoctlTk.cpp:5:
/mnt/nvme2n1/wayne/beegfs/beegfs/client_devel/include/beegfs/beegfs_ioctl.h:7:10: fatal error: uapi/beegfs_client.h: No such file or directory
    7 | #include <uapi/beegfs_client.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [ctl/CMakeFiles/ctl.dir/build.make:76: ctl/CMakeFiles/ctl.dir/source/toolkit/IoctlTk.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:677: ctl/CMakeFiles/ctl.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
root@hpeesx01-salab:/mnt/nvme2n1/wayne/beegfs/beegfs/build1# 
```

**Expected behavior**
cmake .. should build binary well

**Log messages, error outputs**
If available, add relevant log files (anonymize if necessary), error messages, `perf` measurements, `strace` outputs, core dumps and everything else you have collected and can share publicly.

**Additional context**
Add any other context not covered above.

**Comment by philippfalk** [comment]
Hello @gaowayne, thank you for reporting this issue with the cmake build. I have pushed a patch to our internal repository that will be included in the next release and fixes the issue you reported by adding the missing include path. It also fixes a number of other smaller issues with missing source files in various `CMakeList`s files and adds some compiler flags we also use in our `Makefile`s to avoid excessive warning messages.

I also want to mention that the recommended way to build the project is to use the `Makefile`s as described in the [README](https://github.com/ThinkParQ/beegfs/blob/master/README.md). The main reason for the additional `CMakeList`s is to generate a `compile_commands.json` which is used by language servers to provide integration with code editors and IDEs.
